### ISSUE TITLE
상품 재고 관리를 위한 테이블 생성 및 기능 추가

### ISSUE THREAD

**Issue by HEEpage** [f-lab-edu/olive_youth#9]
### 설명
- 상품별 재고 관리를 위한 Stock 테이블을 생성하고, Product 테이블에서 `inventory_quantity` 필드로 관리했던 재고 수량을 Stock 테이블의 개별 레코드로 대체한다.
- 수량 처리와 관련한 모든 기능을 새로 생성한 Stock 테이블과 연동하여 기존 로직이 정상적으로 작동하도록 수정한다.

### TO-DO
- [x] Stock 테이블을 생성하고 Product 테이블과 관계 설정
- [x] 상품 등록 시 입력한 개수만큼 Stock 테이블에 해당 개수의 레코드 생성
- [ ] 상품 재고 수량 추가 시 해당 개수만큼 Stock 테이블에 레코드 추가
- [x] Stock 테이블에서 status 필드로 재고 현황 관리 (사용가능, 예약 중, 판매완료) -> (사용가능, 판매완료)로 변경함
